### PR TITLE
New Feature - Split Artwork by Media Source

### PR DESCRIPTION
**Pull request by redglory**
With this new feature you can split your artwork based on your media source instead of just by media content.

### CODE REVIEW

**Comment by ronie** [comment]
thanx for these!

the only part i'm not sure of is changing the addon id?
if you change it, users won't get an automatic update when this is submitted to the addon repo.

**Comment by ronie** [comment]
merging anyway :-)

but please let me know about the addon id, i'll probably change it back
but if you have a reason to keep it, i can always revert it.

**Comment by redglory** [comment]
Hi @ronie

I've chanceg the addon id because i got the impression you wouldn't want to maintain it.

Of course you can change the add-on I'd

Cheers

**Comment by ronie** [comment]
> I've chanceg the addon id because i got the impression you wouldn't want to maintain it.

that's correct, i wouldn't mind if you would take it over :-)
if you want to, you can keep the addon-id and submit your version to the addon repo from now on.
just let me know... i can also close my support thread on the forum and direct users to yours.

**Comment by redglory** [comment]
Ok, I'll take it from here, if you don't mind.

You already have your hands full :)

**Comment by ronie** [comment]
great, thx!
much appreciated :-)

**Pull request merged**
